export { Adm as AdmPage } from "./Adm"
export { Home as HomePage } from "./Home"
export { Cadastrar as CadastrarPage } from "./Cadastrar"
export { Layout as LayoutPage } from "./Layout"
export { Login as LoginPage } from "./Login"
